version: "3.8"

services:
  web:
    container_name: web
    image: nginx:1.15.2
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../app:/var/www/html

  app:
    container_name: app-my-project
    build: ./
    depends_on:
      - db
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ../app:/var/www/html

  db:
    container_name: db
    image: mysql:5.7.23
    environment:
      - MYSQL_DATABASE=my_app
      - MYSQL_USER=my_app
      - MYSQL_PASSWORD=secret
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - TZ=Japan
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - db-my-project:/var/lib/mysql

  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "9090:80"

volumes:
  db-my-project: